server:
  port: 8010


spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            test:
              - uri: http://client:client@localhost:8030/
                metadata:
                  management.context-path: /actuator
    
instance:
  hostname: localhost